### ISSUE TITLE
XML Parse error in `get_sso_cookies` if CERN SSO is malfunctioning

### ISSUE THREAD

**Issue by nothingface0** [CMSTrackerDPG/cernrequests#2]
Seems like CERN SSO temporarily fails to accept SSL certificates when trying to login. I was told that [this is temporary](https://cern.service-now.com/service-portal?id=outage&n=OTG0070623).

Trying to use my generated grid credentials on [this page](https://login.cern.ch/adfs/ls/auth/sslclient/) results in the following error:
![image](https://user-images.githubusercontent.com/8612771/166237669-6729a87e-5aef-4bb9-b1b8-e7e0b9d7fe77.png)

This leads to `get_sso_cookies` failing to run the `_extract_login_form`. 

To reproduce:
```python3
import cernrequests

url = 'https://cmsrunregistry.web.cern.ch/'
c = cernrequests.get(url, verify=False)
c = cernrequests.cookies._construct_certificate_authentication_url(c.url) 
c = cernrequests.get(url=c, verify=False)
cernrequests.cookies._extract_login_form(c.content)
``` 

Now, `c` contains the resulting page shown in the screenshot above. 

Trying to parse this with `_extract_login_form`, results in `ParseError('not well-formed (invalid token): line 121, column 69')`.

Should this be caught earlier (i.e. if ` Authentication failed. Please close the browser and try again.` is contained in `c`), so that the package raises an more informative Exception instead of crashing?

**Comment by nothingface0** [comment]
@avivace @fabioespinosa Are you still using this library? Should I update this?

**Comment by avivace** [comment]
> @avivace @fabioespinosa Are you still using this library? Should I update this?

Yes, I'm still using it as it's still the only way to get data from services without an API auth system (e.g. cds)

I also, remember someone else at CERN had a separately maintained fork on gitlab..

**Comment by nothingface0** [comment]
I see two forks:
- https://github.com/fabioespinosa/cernrequests
- https://github.com/aminnj/cernrequests

Both not updated since 2019. Are there any other ones I'm not aware of?

I believe that the current one is the one used for the PyPI package, though.

**Comment by pmandrik** [comment]
Hi, we (CMS DQM) are using this as a part of Run Registry API provided to obtain the data from [0]. Consequentially, the API is used also by subsistems for data certification.

[0] https://cmsrunregistry.web.cern.ch/

**Comment by nothingface0** [comment]
Thanks for your report @pmandrik. I already contacted Single Sign On and Account Management Services to raise a ticket, and they told me that it's part of an ongoing outage. 

From my limited understanding and testing, there's no fix to that other than waiting for the CERN SSO service to fix that. In the meantime, the `cernrequests` module could be modified to at least raise an appropriate exception, as stated above. 

I might be missing something. Might there be another solution to this?

**Comment by nothingface0** [comment]
@pmandrik @avivace The issue seems to be fixed now.

**Comment by francescobrivio** [comment]
Thanks for reporting @nothingface0!
As downstream user of the `cmsrunregistry` linked above I can confirm the issue seems gone on our side, I let @pmandrik confirm further if everything looks as expected.

**Comment by pmandrik** [comment]
Hi, @nothingface0 , thank you for the notification. Authentication with cernrequests is working for me now, also there is a confirmation from subsystems https://github.com/cms-DQM/runregistry/issues/12

**Comment by nothingface0** [comment]
Thanks for your reports @francescobrivio and @pmandrik ! Closing this.

**Comment by avivace** [comment]
> Thanks for reporting @nothingface0! As downstream user of the `cmsrunregistry` linked above I can confirm the issue seems gone on our side, I let @pmandrik confirm further if everything looks as expected.

I can confirm the issue is fixed too
